CREATE TABLE IF NOT EXISTS LOGIN_CREDENTIALS ( USER_ID TEXT PRIMARY KEY, PASSWORD TEXT, LOGIN_STATUS INT, LOGIN_TIME TIMESTAMP, LOGIN_IP TEXT, ENABLED BOOLEAN);

CREATE TABLE IF NOT EXISTS AUTHORITIES ( USER_ID TEXT, AUTHORITY TEXT, PRIMARY KEY (USER_ID, AUTHORITY) );

INSERT INTO LOGIN_CREDENTIALS (USER_ID, PASSWORD, ENABLED) VALUES ('255323', 'secret', true);

INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUES ('255323', 'ADMIN');
